name: CI
on: pull_request

jobs:
  warn-big-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cornell-dti/big-diff-warning@master
        env:
          BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Secret Files
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          SECRET_KEYS_XML: ${{ secrets.SECRET_KEYS_XML }}
        run: |
          echo $GOOGLE_SERVICES_JSON > Density/app/google-services.json
          echo $SECRET_KEYS_XML > Density/app/src/main/res/values/secret_keys.xml
      - name: Build with Gradle
        run: cd Density/app/ && gradle build
